### ISSUE TITLE
More info on Data Augmentation

### ISSUE THREAD

**Issue by vitchor** [benjaminlyons/league-pb-predictor#1]
Hey! I'm trying to build a lol pd predictor as a study project (I'm taking a course on ML). And, I've seen in [this article](http://www.tsinzitari.com/Portfolio/Predicting%20Pick-Ban%20Sequence%20in%20League%20of%20Legends%20Games.pdf) you wrote that you've also implemented some data augmentation (using the pickRate, banRate, etc), to enhance the input features.

Could you share, by any chance, the code you've used to augment the features vector? I couldn't find it in this repo. Thank you thank you! 🙏 
cc @tim-inzitari

**Comment by tim-inzitari** [comment]
Hello,

If the code wasn't committed ( i thought I did) It is gone now. I wiped the local of it over a year ago.

I remember having to make a custom layer in pytorch or tensorflow (forget what we used) from scratch pretty much and just inputting it into the pipeline. Goodluck

**Comment by vitchor** [comment]
Thank you so much for the speedy reply, @tim-inzitari. 

Quick question: once you've added the new features, the number of inputs doubled, right? I'd like to make sure that the new values (pickRate, banRate, etc) were appended to the existing input vector (and they didn't replace the previous champions' inputs).

Btw, your article and repo inspired me a lot! Thank you! 😃

**Comment by vitchor** [comment]
@tim-inzitari ?
